name: Build and Release APK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Unit Tests
        run: ./gradlew test --stacktrace
      - name: Assemble Project
        run: ./gradlew assemble --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: Atari_Breakout
          path: app/build/outputs/apk/debug/app-debug.apk
